Fix the navbar #40 issue complete
ROBOTICS-CLUB-IIITDMJ/ERS-frontend pull request #45
Opened 2021-08-09 16:21 UTC by Jake-Januszanis

## Summary
Fixed issue #40 

## Solution 
 - Refactored the code and updated class names using BEM naming convention
 - Removed Navbar.Toggle & Navbar.Collapse since it didn't seem to be needed and was causing position issues

## Notes 
 - Navbar is not responsive but can be updated if breakpoints are provided

## Tested browsers
- [x] Chrome

2021-08-10 18:03 UTC, somya51p requested changes

2021-08-10 18:03 UTC, somya51p commented on src/components/Navbar/Navi.jsx
> -                <Navbar.Collapse id="basic-navbar-nav">
@Jake-Januszanis We need `Collapse`, if it is creating some issue, will resolve it further. But don't remove `Navbar.Toggle` & `Navbar.Collapse`

2021-08-10 21:42 UTC, Jake-Januszanis commented on src/components/Navbar/Navi.jsx
> -                <Navbar.Collapse id="basic-navbar-nav">
Okay, no problem. I will add it in now.

2021-08-11 03:51 UTC, somya51p commented
@Jake-Januszanis `Collapse` is not working. Please look into that. Also, squash the commits into one.

2021-08-11 04:50 UTC, somya51p commented on src/components/Navbar/Navi.jsx
> +            <button type='button' class='btn btn-danger nav__btn'>Sign In</button>
Include `signup` button inside `Navbar.Collapse`.

![Screenshot from 2021-08-11 09-24-41](https://user-images.githubusercontent.com/64978837/128967135-3e2e3cf5-9a64-4d1f-9b84-1150cdfc88b3.png)

2021-08-11 17:48 UTC, Jake-Januszanis commented on src/components/Navbar/Navi.jsx
> +            <button type='button' class='btn btn-danger nav__btn'>Sign In</button>
Will do!

2021-08-11 17:56 UTC, Jake-Januszanis commented on src/components/Navbar/Navi.jsx
> +            <button type='button' class='btn btn-danger nav__btn'>Sign In</button>
Okay, I added the button into the Collapse component and squashed my commits. Let me know if everything looks good.

2021-08-12 04:15 UTC, somya51p commented
@Jake-Januszanis It's perfectly fine with large devices, please have a look with mobile devices. And try to resolve it.

![Screenshot from 2021-08-12 09-41-21](https://user-images.githubusercontent.com/64978837/129137252-ac7c4bc9-b5a8-4f67-8a07-795382909a2e.png)
![Screenshot from 2021-08-12 09-41-32](https://user-images.githubusercontent.com/64978837/129137256-99f91c39-0c00-4790-be80-069a77bbc1ae.png)

2021-08-12 14:10 UTC, Jake-Januszanis commented
Okay, I updated the navbar so now it will collapse into a dropdown menu for mobile devices.
The mobile navbar still needs to be styled and worked on. 
As for issue #40 that should be complete now. The layout and font size are both updated.
Let me know if there are any issues.
@somya51p

2021-08-12 16:45 UTC, somya51p commented
> Okay, I updated the navbar so now it will collapse into a dropdown menu for mobile devices.
> The mobile navbar still needs to be styled and worked on.
> As for issue #40 that should be complete now. The layout and font size are both updated.
> Let me know if there are any issues.
> @somya51p

Good work!!

2021-08-12 16:46 UTC, merged